export const ErrorMsgs = {
	authRequired: 'Authorization required',
	invalidAuthType: 'Invalid authorization type',
	invalidBody: 'Invalid body request',
	invalidRefreshToken: 'Invalid refresh token',
	invalidSignature: 'Invalid signature',
	invalidUsernamePasswd: 'Invalid username and/or password',	
	missingFinished: 'Missing required field: finished',
	missingOldPassword: 'Missing required field: old password',
	missingParamId: 'Missing parameter id',
	missingPasswd: 'Missing required field: password',
	missingRefreshToken: 'Missing body field: refreshToken',
	missingUsername: 'Missing required field: username',
	missingUsernameAndPasswd: 'Missing required fields: username and password',
	noEmptyPassword: 'Password cannot be empty',
	unableToDeleteHistory: 'Unable delete history because has tasks associated to it',
	unableToDeleteTask: 'Unable delete task because has timeTable associated to it',
	usernameExist: 'Username already exists',
	userNotFound: 'User not found',
};
